name: Get/Build Solo5 artifacts

on:
  workflow_call:
    inputs:
      solo5_version:
        description: 'Solo5 version to build'
        type: string
        required: false
        default: 'v0.9.3'
      arch:
        description: 'The CPU architecture to build Solo5'
        type: string
        required: false
        default: '["amd64", "arm64"]'
      runner-arch-map:
        description: 'Mapping of CPU architecture to runner names'
        type: string
        required: false
        default: '{"amd64":"ubuntu-22.04", "arm64":"ubuntu-22.04-arm"}'
    outputs:
      artifact_suffix:
        description: 'The suffix of the Solo5 artifacts (version)'
        value: ${{ jobs.summarize-info.outputs.suffix }}
      artifact_run_id:
        description: 'The run id that built the Solo5 artifacts'
        value: ${{ jobs.summarize-info.outputs.run_id }}

jobs:
  check-artifact-existence:
    runs-on: ubuntu-latest
    outputs:
      suffix: ${{ inputs.solo5_version }}
      exists: ${{ steps.search.outputs.exists }}
      run_id: ${{ steps.search.outputs.run_id }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Search for Solo5-hvt amd64 artifact
        id: search_hvt_amd64
        uses: ./.github/actions/get-artifact-info/
        with:
          name: solo5-hvt-amd64-${{ inputs.solo5_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Search for Solo5-hvt arm64 artifact
        id: search_hvt_arm64
        uses: ./.github/actions/get-artifact-info/
        with:
          name: solo5-hvt-arm64-${{ inputs.solo5_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Search for Solo5-spt amd64 artifact
        id: search_spt_amd64
        uses: ./.github/actions/get-artifact-info/
        with:
          name: solo5-spt-amd64-${{ inputs.solo5_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Search for Solo5-spt arm64 artifact
        id: search_spt_arm64
        uses: ./.github/actions/get-artifact-info/
        with:
          name: solo5-spt-arm64-${{ inputs.solo5_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Summarize search results
        id: search
        run: |
          if [[ ${{ steps.search_hvt_amd64.outputs.exists }} == 'false' ]] || \
             [[ ${{ steps.search_hvt_arm64.outputs.exists }} == 'false' ]] || \
             [[ ${{ steps.search_spt_amd64.outputs.exists }} == 'false' ]] || \
             [[ ${{ steps.search_spt_arm64.outputs.exists }} == 'false' ]]
          then
            echo "One of the artifacts was not found"
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "run_id=" >> $GITHUB_OUTPUT
            echo "download_url=" >> $GITHUB_OUTPUT
          else
            if [[ ${{ steps.search_hvt_amd64.outputs.run_id }} != ${{ steps.search_hvt_arm64.outputs.run_id }} ]] || \
               [[ ${{ steps.search_hvt_amd64.outputs.run_id }} != ${{ steps.search_spt_amd64.outputs.run_id }} ]] || \
               [[ ${{ steps.search_hvt_amd64.outputs.run_id }} != ${{ steps.search_spt_arm64.outputs.run_id }} ]]
            then
              echo "Artifacts were built with different run id"
              echo "exists=false" >> $GITHUB_OUTPUT
              echo "run_id=" >> $GITHUB_OUTPUT
              echo "download_url=" >> $GITHUB_OUTPUT
            else
              echo "Found them"
              echo "exists=true" >> $GITHUB_OUTPUT
              echo "run_id=${{ steps.search_hvt_arm64.outputs.run_id }}" >> $GITHUB_OUTPUT
              echo "download_url=${{ steps.search_hvt_arm64.outputs.download_url }}" >> $GITHUB_OUTPUT
            fi
          fi

  build-Solo5:
    name: Build Solo5 static binaries
    needs: [check-artifact-existence]
    if: ${{ needs.check-artifact-existence.outputs.exists == 'false' }}
    strategy:
      matrix:
        arch: ${{ fromJSON(inputs.arch) }}
    runs-on: ${{ fromJSON(inputs.runner-arch-map)[matrix.arch] }}
    outputs:
      run_id: ${{ github.run_id }}
    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install base dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libseccomp-dev pkg-config bc

      - name: Build Solo5-hvt and Solo5-spt
        run: |
          git clone -b ${{ inputs.solo5_version }} https://github.com/Solo5/solo5.git solo5_source
          cd solo5_source
          sed -i '66 a\HOSTLDFLAGS += -static-pie' tenders/GNUmakefile
          ./configure.sh && make -j$(nproc)
       
      - name: Archive Solo5-hvt artifact
        uses: actions/upload-artifact@v4
        with:
          name: solo5-hvt-${{ matrix.arch }}-${{ needs.check-artifact-existence.outputs.suffix }}
          path: solo5_source/tenders/hvt/solo5-hvt
       
      - name: Archive Solo5-spt artifact
        uses: actions/upload-artifact@v4
        with:
          name: solo5-spt-${{ matrix.arch }}-${{ needs.check-artifact-existence.outputs.suffix }}
          path: solo5_source/tenders/spt/solo5-spt

  summarize-info:
    runs-on: ubuntu-latest
    needs: [check-artifact-existence, build-Solo5]
    if: ${{ !cancelled() }}
    outputs:
      suffix: ${{ needs.check-artifact-existence.outputs.suffix }}
      run_id: ${{ steps.info.outputs.run_id }}
    steps:
      - name: Produce correct artifact info
        id: info
        run: |
          if [[ "${{ needs.check-artifact-existence.outputs.exists }}" == "false" ]]
          then
            echo "run_id=${{ needs.build-Solo5.outputs.run_id }}" >> $GITHUB_OUTPUT
          else
            echo "run_id=${{ needs.check-artifact-existence.outputs.run_id }}" >> $GITHUB_OUTPUT
          fi
